---
title: "Billboard Hot 100 Analysis (2000-2018)"
output: 
  flexdashboard::flex_dashboard:
runtime: shiny
---

```{r context="setup", include=FALSE}
#importing the required libraries
library(flexdashboard)
library(DT)
library(lubridate) #to format dates, which are not in an ideal format
library(shiny)
library(dplyr)
library(ggplot2)
library(data.table)# to perform substring match

#data preprocessing and reactivity

#importing the dataset
billboard_data <- read.csv("C:/Users/prakh/Desktop/Semester III/R Shiny/Homework 2/billboard.csv")

#extracting the year from the date
a=mdy(billboard_data$date)
billboard_data$year<-(year(a))

# Rename "year" column to years to avoid mix up with year() function in lubridate
colnames(billboard_data)[colnames(billboard_data)=="year"] <- "years"

#dropping unnecessary "date" column
billboard_data = subset(billboard_data, select = -c(date) )


```



#Sidebar {.sidebar}

```{r context="render"}

#X-axis variable
selectInput(inputId = "y", 
            label = "Y-axis:",
            choices = c("Tempo" = "tempo", 
            "Duration" = "duration_ms",
            "Loudness" = "loudness",
            "Energy"="energy"),
            selected = "Tempo")


checkboxGroupInput("years", "Select the year of release for the song:", 
                   choices = c("2000","2001","2002","2003",
                               "2004","2005","2006","2007","2008",
                               "2009","2010","2011","2012","2013",                                                         "2014","2015","2016","2017","2018"),
                   selected = c("2018"), 
                   inline = TRUE)


sliderInput("peak", "Filter by the tracks peak position",
            min = min(billboard_data$peak_pos), max = max(billboard_data$peak_pos),
            value = range(billboard_data$peak_pos)
            )


```


Data Table {data-icon="fa-table"}
=====================================


```{r context="server"}

# Subsetting data for filtering based on selection of year of release
billboard_subset <- reactive({
  billboard_data%>%
  filter(
    years %in% input$years,
      peak_pos >= input$peak[1],
      peak_pos <= input$peak[2]
  )
})

output$DataTable <- DT::renderDataTable(
    DT::datatable(data = billboard_subset()[,-30], 
                  options = list(pageLength = 50, scrollY="300px"), 
                  rownames = FALSE)
)
```


```{r context="render"}
dataTableOutput("DataTable")
```

Top Artists {data-icon="fa-headset"}
=====================================

```{r context="server"}
top_artists <- reactive({billboard_subset() %>%
    group_by(artist)  %>%
    summarise(n_apperance = n()) %>%
    filter(n_apperance > 1) %>%
    arrange(desc(n_apperance))%>% slice(1:10)
})
#pre-setting the black and white theme
theme_set(theme_bw())

output$plotBar <-renderPlot({
    ggplot(top_artists(), aes(x = artist, y=n_apperance)) +
    geom_bar(stat = "identity",  fill = "slateblue3", width = 0.6 ) +
     labs(title = "Top Artists", subtitle="Which artists had the most songs in the Hot 100 in the selected years?",x = "Artists", y = "Number of Apperance on the Top 100") +
     theme(plot.title = element_text(size=15,hjust=-.3,face = "bold"), axis.title =   element_text(size=12)) +
     geom_text(aes(label=top_artists()$n_apperance), hjust = 2, size = 3, color = 'white') +
     coord_flip()
})
```


```{r context="render"}
plotOutput("plotBar")
```

Musical Characterstics {data-icon="fa-music"}
=====================================

```{r context="server"}

output$plotDensity<-renderPlot({
  g <- ggplot(billboard_subset(), aes(key, input$y))
g + geom_violin()+ 
  labs(title="Musical Key Distribution", 
       subtitle="In music theory, the key of a piece is the group of pitches, or scale, that forms the basis of a music composition in classical, Western art, and Western pop music.",
       x="Artist",
       y=input$y)
  g + geom_jitter(aes(col=key, size=input$y )) + 
  geom_smooth(aes(col=key), method="lm", se=F)
})
```

```{r context="render"}

plotOutput("plotDensity")

```



Artist Characteristics {data-icon="fa-user-circle"}
=====================================
```{r context="server"}

top_mode <- reactive({billboard_subset() %>%
    group_by(mode)  %>%
    summarise(n_apperance = n()) %>%
    filter(n_apperance > 1) %>%
    arrange(desc(n_apperance))%>% slice(1:10)
})

output$plotSeasonal <- renderPlot({

ggplot(top_mode(), aes(mode))+ 
    geom_bar(aes(fill=mode), width = 0.5) + 
    theme(axis.text.x = element_text(angle=65, vjust=0.6)) +
    labs(title="Musical Mode Distribution", 
       subtitle="While there exist seven musical modes in music, we notice that only two are largely followed by songs in the Hot 100", 
       caption="In the theory of Western music, a mode is a type of musical scale coupled with a set of characteristic melodic behaviors.",
       y= input$y)
  
}) 

```


```{r context="render"}

plotOutput("plotSeasonal")

```


